FROM node:14.15.3-alpine
WORKDIR /app/frontend
#Copy package.json and package-lock.json before other files
COPY /frontend/package*.json /app/frontend/
RUN npm ci
#Copy everything that is not in .dockerignore to /app/frontend/
COPY /frontend/ /app/frontend/
#Copy entrypoint file
COPY /docker/frontend/staging/entrypoint.sh /app/frontend/
#RUN npm run build
#CMD ["npm", "start"]
#ENTRYPOINT [ "/app/frontend/entrypoint.sh" ]