version: '3.8'

services:
    # nginx: 
    #     #restart: unless-stopped
    #     container_name: nginx_
    #     build:
    #         context: .
    #         dockerfile: /docker/nginx/dev/Dockerfile
    #     ports:
    #         - 8080:8080
    #     volumes:
    #         - static_volume:/app/django_static
    #         - /docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on: 
    #         - frontend

    frontend: 
        #restart: unless-stopped
        container_name: frontend_
        build:
            context: .
            #works with absolute path like this but not relative or env path
            #dockerfile: C:\Users\MyCod\Coding Projects\Python Projects\Project-Director\docker\frontend\dev\DockerFile
            dockerfile: /docker/frontend/dev/Dockerfile
        expose:
            - 3000
        depends_on: 
            - backend

    backend:
        #restart: unless-stopped
        container_name: backend_
        build:
            context: .
            dockerfile: /docker/backend/dev/Dockerfile
        volumes:
        env_file:
            - ./.env.dev
        entrypoint: 
            - /app/backend/entrypoint.dev.sh
        volumes:
            - static_volume:/app/django_static
        expose:
            - 8000
        depends_on:
            - db
    db:
        image: postgres:13
        container_name: dev-db
        #port:
        expose: 
            - 5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${SQL_DATABASE}        

volumes:
    static_volume:
    postgres_data: