version: "3.8"

services:
  dev_frontend:
    #restart: unless-stopped
    container_name: dev_frontend
    build:
      context: .
      dockerfile: /docker/frontend/dev/Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      #map host directory to docker directory to detect changes
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/.next
    ports:
      #expose port to browser
      - 3000:3000
    depends_on:
      - backend

  dev_backend:
    #restart: unless-stopped
    container_name: dev_backend
    build:
      context: .
      dockerfile: /docker/backend/dev/Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      #map host directory to docker directory to detect changes
      - ./backend:/app/backend
      - /usr/local/lib/python3.9/site-packages
    ports:
      #so the admin dashboard can be tested
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: dev_db
    #port:
    expose:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
